/**
 * Generates public/sitemap.xml from the real product catalog and a
 * small list of static routes — run automatically before every build
 * (see package.json's "build" script) so the sitemap never drifts out
 * of sync with the catalog. Only public, indexable pages are listed:
 * account/cart/checkout/wishlist/order-confirmation are intentionally
 * excluded (see public/robots.txt) since they're per-customer/
 * transactional, not content Google should index.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { products } from '../src/data/products.js';
import site from '../src/config/site.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, '../public/sitemap.xml');
const baseUrl = site.seo.siteUrl;

const staticRoutes = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/shop', changefreq: 'daily', priority: '0.9' },
  { path: '/shop?category=shoes', changefreq: 'daily', priority: '0.8' },
  { path: '/shop?category=clothing', changefreq: 'daily', priority: '0.8' },
  { path: '/shop?category=big-tall', changefreq: 'daily', priority: '0.8' },
  { path: '/size-guide', changefreq: 'monthly', priority: '0.5' },
  { path: '/about', changefreq: 'monthly', priority: '0.4' },
  { path: '/contact', changefreq: 'monthly', priority: '0.4' },
  { path: '/su-passport', changefreq: 'monthly', priority: '0.3' },
  { path: '/faqs', changefreq: 'monthly', priority: '0.3' },
  { path: '/delivery', changefreq: 'monthly', priority: '0.3' },
  { path: '/returns', changefreq: 'monthly', priority: '0.3' },
  { path: '/privacy-policy', changefreq: 'yearly', priority: '0.1' },
  { path: '/terms', changefreq: 'yearly', priority: '0.1' },
];

const productRoutes = products.map((p) => ({
  path: `/product/${p.slug}`,
  changefreq: 'weekly',
  priority: '0.7',
}));

const urls = [...staticRoutes, ...productRoutes];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Auto-generated by scripts/generate-sitemap.js — do not edit by hand. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) => `  <url>
    <loc>${baseUrl}${u.path}</loc>
    <changefreq>${u.changefreq}</changefreq>
    <priority>${u.priority}</priority>
  </url>`
  )
  .join('\n')}
</urlset>
`;

writeFileSync(outPath, xml, 'utf8');
console.log(`Generated sitemap.xml with ${urls.length} URLs (${productRoutes.length} products).`);
